language: node_js
sudo: false
node_js:
  - '6.6.0'

cache:
  directories:
    - $HOME/.chrome/chromium

before_install:
  - ./scripts/install_chromium.sh
  - export CHROME_BIN=$HOME/.chrome/chromium/chrome-linux/chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm run build

script:
  - npm test